#pragma once

#include <pebble.h>

#define NUM_VRAMS 4
#define NUM_BACKGROUNDS 4
#define SCREEN_WIDTH 184
#define SCREEN_HEIGHT 184
#define SCREEN_X_OFFSET (SCREEN_WIDTH - PBL_DISPLAY_WIDTH) / 2
#define SCREEN_Y_OFFSET (SCREEN_HEIGHT - PBL_DISPLAY_HEIGHT) / 2

#define BG_LAYER 0
#define FG_LAYER 1
#define TIME_LAYER 2
#define SPRITE_LAYER 2
#define MASK_LAYER 3

#define MASK_PALETTE_NUM (GBC_PALETTE_NUM_PALETTES - 1)
#define MASK_VRAM_NUM 1
#define MASK_LEVELS 5
#define MASK_VRAM_OFFSET (GBC_VRAM_BANK_NUM_TILES - 1 - MASK_LEVELS)

#define NUMBER_HEIGHT 5
#define NUMBER_WIDTH 3
#define TOTAL_NUMBERS 11

#define LITTLE_NUMBER_HEIGHT 3
#define LITTLE_NUMBER_WIDTH 2
#define TOTAL_LITTLE_NUMBERS 12

#define FRAME_DURATION 125 // In ms

#define SECONDS_BETWEEN_STEPS 1

#define TIME_X_TILE_OFFSET 3
#define TIME_Y_TILE_OFFSET 6
#define TIME_Y_PIXEL_SHIFT 4

#define DATE_X_TILE_OFFSET (TIME_X_TILE_OFFSET + 3)
#define DATE_Y_TILE_OFFSET (TIME_Y_TILE_OFFSET - (LITTLE_NUMBER_HEIGHT + 1))

#define NUM_POKEMON_SPRITE_ACTORS 3
#define NUM_SPRITE_ACTORS (1 + NUM_POKEMON_SPRITE_ACTORS)
#define SPRITE_BOTTOM_Y 136
#define BG_STEP_SIZE 2
#define FG_STEP_SIZE 2
#define SPRITE_STEP_SIZE 4
#define SPRITE_DATA_BYTES_PER_FRAME 3

#define NUM_POKEMON 155
#define BYTES_PER_POKEMON_DATA 19
#define POKEMON_SPRITE_BOTTOM_Y (SPRITE_BOTTOM_Y - 1)
#define NUM_POKEMON_FRAMES 2
#define PIXELS_BETWEEN_SPRITES 2

#define CHARACTER_RANDOM 0
#define CHARACTER_RED 1
#define CHARACTER_LEAF 2

#define POKEMON_RANDOM 0
#define POKEMON_NONE 1
#define POKEMON_CHOOSE 2

#define SETTINGS_KEY 0

#define DEMO_MODE false